name: CI - Lacrei Saúde Consultas Médicas - Api

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Cria um banco de dados temporário dentro do GitHub Actions
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: lacrei_db
          POSTGRES_USER: lacrei_user
          POSTGRES_PASSWORD: lacrei_pass
        ports:
          - 5432:5432
        # Espera o banco estar pronto antes de continuar
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    # Baixa o código
    - uses: actions/checkout@v3

    # Instala o Python
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    # Instala o Poetry
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    # Instala dependências (cache para ser mais rápido nas próximas vezes)
    - name: Install Dependencies
      run: poetry install --no-interaction --no-root

    # Roda os Testes
    - name: Run Tests
      env:
        # passando as credenciais do banco temporário criado lá em cima
        DATABASE_URL: postgres://lacrei_user:lacrei_pass@localhost:5432/lacrei_db
        SECRET_KEY: 'secret-key-de-teste-ci'
        DEBUG: 'True'
      run: |
        poetry run python manage.py test


  # --------------------------------------------------


  deploy:
    # Só roda se o push for para a branch principal (main ou master)
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: test # Só roda o deploy se o job 'test' passar
    runs-on: ubuntu-latest
    
    

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Configura as credenciais da AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        # Pega as Secrets que configurou no GitHub
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }} # Ex: us-east-1 - da a aws que esta usando

    # Faz o Deploy para o Elastic Beanstalk
    - name: Deploy to Elastic Beanstalk
      uses: aws/elastic-beanstalk-deploy@v1
      
      with:
        application_name: lacreiconsultasmedicasapi # O nome que deu ao aplicativo no EB
        environment_name: Lacreiconsultasmedicasapi-env # O nome do ambiente que o EB está criando
        # O nome do arquivo zip que o EB espera. O default é app.zip
        deployment_package: application.zip 

    # Cria o ZIP do código para o Beanstalk
    - name: Create ZIP Deployment Package
      run: |
        # Cria o pacote com os arquivos necessários, ignorando os de teste
        zip -r application.zip . -x "*.git*" "test_*.py" "*.DS_Store" "*__pycache__*" "*.venv*" "*.github*" "db.sqlite3"